### ISSUE TITLE
Improving accessibility by query string parameters?

### ISSUE THREAD

**Issue by mgiugliano** [nealey/vail-adapter#2]
Visually impaired users might benefit from directly accessing settings (i.e. mode and WPM) via the Query String. This would make it possible to bookmark just the URL and go there, similarly to the style of accessing the "repeaters".

e.g. https://vail.woozle.org/#3?wpm=21&mode=iambicb

They would then be immediately "on the air", even without setting cookies.

I have the gut feeling something (a bit more verbose) can be already done through adding a JS function to the URL, but it might be blocked for security reason. Apologies for my lack of knowledge.

**Comment by nealey** [comment]
The right way to do this would be to pop up a dialog saying something like "the link you used to get here would like to change your Keyser mode to Iambic B, set the WPM to 40, and use telegraph sounds. These settings will persist until you change them. Would you like to allow this?"

That's a substantial amount of code. If someone would like to submit a patch to do this, I'm open to it, but it's not something I'm likely to do myself. Sorry.

Also, this ticket is on the Vail adapter codebase. You probably meant to open it against Vail proper. So I'm going to close it, since the adapter doesn't even know what a URL is 😉
